HRSystem/Controllers/AttentanceReportController.cs
using HRSystem.Models;
using HRSystem.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

using System.Threading.Tasks;
using System.Data;
using System.Data.OleDb;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using Microsoft.Data.SqlClient;


namespace HRSystem.Controllers
{
    public class AttentanceReportController : Controller
    {
        IDepartmentRepository departmentRepository;
        IEmployeeRepository employeeRepository;
        IAttentanceReportRepository attentanceReportRepository;
        public AttentanceReportController(IDepartmentRepository department, IAttentanceReportRepository attentance, IEmployeeRepository employee)
        {
            departmentRepository = department;
            employeeRepository = employee;
            attentanceReportRepository = attentance;
        }

        public IActionResult Index(int ID=0,string EmpName = null, int DeptID = 0, System.DateTime DateFrom = new System.DateTime(), System.DateTime DateTo = new System.DateTime())
        {           //Get All Reports with filtring

            List<AttendanceReport> reports = attentanceReportRepository.GetAll();
            List<Department> departments = departmentRepository.GetAll();
            string namerr = "";
            if (EmpName != null)
            {
                reports = reports.Where(e => e.Employee.Name.Contains(EmpName)).ToList();
                if (reports.Count == 0)
                {
                    namerr = "Enter Valid Name";
                }
            }

            if (DeptID != 0)
            {
                reports = reports.Where(e => e.Employee.DeptID == DeptID).ToList();
            }
            string msg = "";
            if (DatePeriod(DateFrom, DateTo))
            {
                reports = reports.Where(r => r.Date >= DateFrom && r.Date <= DateTo).ToList();
            }
            else if(DateFrom.Year != 1) { msg = "Enter Valid Date "; }
            ViewData["EmpName"] = EmpName;
            ViewData["DeptId"] = DeptID;
            ViewData["DateFrom"] = DateFrom;
            ViewData["DateTo"] = DateTo;
            ViewData["Depts"] = departments;
            ViewData["msg"] = msg;
            ViewData["namerr"] = namerr;
            ViewData["id"] = ID;
            return View(reports);
        }


        public IActionResult Create()
        {
            List<Department> departments = departmentRepository.GetAll();//context.departments.ToList();
            ViewData["Depts"] = departments;

            List<Employee> employees = employeeRepository.GetAll();//context.employees.ToList();
            ViewData["emps"] = employees;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAttentance(AttendanceReport attendance)
        {
            if (ModelState.IsValid && attendance.EmpId != 0 && attendance.Date.Year >=2008)
            {
                attentanceReportRepository.Insert(attendance);
                return RedirectToAction("Index");
            }
            return RedirectToAction("create");

        }

        public IActionResult Delete(int id)
        {
            if (id != 0)
            {
                attentanceReportRepository.Delete(id);
            }
            return RedirectToAction("Index");
        }

        //Edit Attendance 
        public IActionResult Edit(int id)
        {
            AttendanceReport att = attentanceReportRepository.GetById(id);
            List<Department> departments = departmentRepository.GetAll();
            ViewData["Depts"] = departments;

            List<Employee> employees = employeeRepository.GetAll();
            ViewData["emps"] = employees;
            return View(att);
        }
        public IActionResult SaveEdit(int id, AttendanceReport newattendance)
        {
            if (ModelState.IsValid == true)
            {
                attentanceReportRepository.Update(id, newattendance);
                return RedirectToAction("Index");
            }

            List<Department> departments = departmentRepository.GetAll();
            ViewData["Depts"] = departments;

            List<Employee> employees = employeeRepository.GetAll();
            ViewData["emps"] = employees;

            return View("Edit", newattendance);

        }


        /// ----------Exce; -----------------------------------//
        /// 
        //public IActionResult Excel()
        //{
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> ImportExcelFile(IFormFile FormFile)
        {
            //get file name
            var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
            //get path
            var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");
            //create directory "Uploads" if it doesn't exists
            if (!Directory.Exists(MainPath))
            {
                Directory.CreateDirectory(MainPath);
            }
            //get file path 
            var filePath = Path.Combine(MainPath, FormFile.FileName);
            using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
            {
                await FormFile.CopyToAsync(stream);
            }

            //get extension
            string extension = Path.GetExtension(filename);


            string conString = string.Empty;

            switch (extension)
            {
                case ".xls": //Excel 97-03.
                    conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
                case ".xlsx": //Excel 07 and above.
                    conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
            }

            DataTable dt = new DataTable();
            conString = string.Format(conString, filePath);

            using (OleDbConnection connExcel = new OleDbConnection(conString))
            {
                using (OleDbCommand cmdExcel = new OleDbCommand())
                {
                    using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                    {
                        cmdExcel.Connection = connExcel;

                        //Get the name of First Sheet.
                        connExcel.Open();
                        DataTable dtExcelSchema;
                        dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                        string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                        connExcel.Close();

                        //Read Data from First Sheet.
                        connExcel.Open();
                        cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                        odaExcel.SelectCommand = cmdExcel;
                        odaExcel.Fill(dt);
                        connExcel.Close();
                    }
                }
            }
            //your database connection string
            conString = @"Data Source=.;Initial Catalog=HrSystem;Integrated Security=True";

            using (SqlConnection con = new SqlConnection(conString))
            {
                using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                {
                    //Set the database table name.
                    sqlBulkCopy.DestinationTableName = "dbo.attendanceReports";
                    sqlBulkCopy.ColumnMappings.Add("Id", "Id");
                    sqlBulkCopy.ColumnMappings.Add("LeavingTime", "LeavingTime");
                    sqlBulkCopy.ColumnMappings.Add("AttendanceTime", "AttendanceTime");
                    sqlBulkCopy.ColumnMappings.Add("Date", "Date");
                    sqlBulkCopy.ColumnMappings.Add("EmpId", "EmpId");
                    con.Open();
                    sqlBulkCopy.WriteToServer(dt);
                    con.Close();
                }
            }
            //if the code reach here means everthing goes fine and excel data is imported into database
            List<Department> departments = departmentRepository.GetAll();
            List<AttendanceReport> reports = attentanceReportRepository.GetAll();

            ViewBag.Message = "File Imported and excel data saved into database";
            ViewData["EmpName"] = "";
            ViewData["DeptId"] = 0;
            ViewData["DateFrom"] = new System.DateTime();
            ViewData["DateTo"] = new System.DateTime();
            ViewData["Depts"] = departments;
            ViewData["msg"] = "";
            ViewData["namerr"] = "";
            return View("Index", reports);
        }
        //// -------------EndExel-------------//
        ///


        /// ------------validation-----------------------------//


        private bool DatePeriod(System.DateTime DateFrom = new System.DateTime(), System.DateTime DateTo = new System.DateTime())
        {
            if (DateFrom.Year < 2008  || DateTo.Year < 2008)
            {
                return false;
            }
            if (DateFrom.Year < DateTo.Year)
            {
                return true;
            }
            else if (DateFrom.Year == DateTo.Year && DateFrom.Month < DateTo.Month)
            {
                return true;
            }
            else if (DateFrom.Year == DateTo.Year && DateFrom.Month == DateTo.Month && DateFrom.Day <= DateTo.Day)
            {
                return true;
            }
            return false;
        }
        public bool testTime(System.DateTime LeavingTime, System.DateTime AttendanceTime)
        {

            if (LeavingTime <= AttendanceTime)
            {
                return false;
            }
            else
            {

HRSystem/Views/AttentanceReport/Create.cshtml
@model AttendanceReport

@{
    SelectList select_dept = new SelectList(ViewBag.Depts, "Id", "Name");
}




<section id="horizontal-form-layouts">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="content-header">Add Employees Attendance</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">

                <div class="card-body">
                    <div class="px-3">
                        <form class="form form-horizontal mt-4" method="post" asp-controller="AttentanceReport" asp-action="AddAttentance">
                            <div class="form-body">

                                <div class="form-group row">
                                    <label class="col-md-3 label-control" asp-for="EmpId">Employee Id </label>
                                    <div class="col-md-9">
                                        <input asp-for="EmpId" type="text" id="projectinput1" class="form-control">
                                        <span asp-validation-for="EmpId"class="text-danger"></span>
                                    </div>

                                </div>

                                <div class=" row form-group">
                                    <label class="col-md-3 label-control" asp-for="AttendanceTime">Attendance time: </label>
                                    <div class="position-relative has-icon-left col-lg-9">
                                        <input type="time" id="timesheetinput5" class="form-control" asp-for="AttendanceTime">
                                        <div class="form-control-position">
                                            <i class="ft-clock"></i>
                                        </div>
                                        <span asp-validation-for="AttendanceTime"class="text-danger"></span>
                                    </div>
                                </div>

                                <div class=" row form-group">
                                    <label class="col-md-3 label-control" asp-for="LeavingTime">Leaving time: </label>
                                    <div class="position-relative has-icon-left col-lg-9">
                                        <input type="time" id="timesheetinput6" class="form-control" asp-for="LeavingTime">
                                        <div class="form-control-position">
                                            <i class="ft-clock"></i>
                                        </div>
                                        <span asp-validation-for="LeavingTime"class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 label-control" asp-for="Date">Date : </label>
                                    <div class="col-md-9">
                                        <input type="date" id="projectinput10" class="form-control" asp-for="Date">
                                        
                                        <span asp-validation-for="Date" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-actions">
                                      <a class="btn btn-danger" asp-action="Index" asp-controller="AttentanceReport"  >Back</a>
                                    <input type="submit" value="Add" class="btn btn-success" />
                                  
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>



</section>

@section Scripts{
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

HRSystem/Views/AttentanceReport/Edit.cshtml
@model AttendanceReport

@{
    SelectList select_dept = new SelectList(ViewBag.Depts, "Id", "Name");
}

<section id="horizontal-form-layouts">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="content-header">Edit Employees Attendance</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">

                <div class="card-body">
                    <div class="px-3">
                        <form class="form form-horizontal mt-4" method="post" asp-controller="AttentanceReport" asp-action="SaveEdit" asp-route-id=@Model.Id>
                            <div class="form-body">

                                <div class=" row form-group">
                                    <label class="col-md-3 label-control" asp-for="AttendanceTime">Attendance time: </label>
                                    <div class="position-relative has-icon-left col-lg-9">
                                        <input type="time" id="timesheetinput5" class="form-control" asp-for="AttendanceTime">
                                        <div class="form-control-position">
                                            <i class="ft-clock"></i>
                                        </div>
                                        <span asp-validation-for="AttendanceTime"></span>
                                    </div>
                                </div>

                                <div class=" row form-group">
                                    <label class="col-md-3 label-control" asp-for="LeavingTime">Leaving time: </label>
                                    <div class="position-relative has-icon-left col-lg-9">
                                        <input type="time" id="timesheetinput6" class="form-control" asp-for="LeavingTime">
                                        <div class="form-control-position">
                                            <i class="ft-clock"></i>
                                        </div>
                                        <span asp-validation-for="LeavingTime"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 label-control" asp-for="Date">Date : </label>
                                    <div class="col-md-9">
                                        <input type="date" id="projectinput10" class="form-control" asp-for="Date">
                                        
                                        <span asp-validation-for="Date"></span>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-success pr-3 pl-3" data-toggle="modal" data-target="#exampleModal">Edit</button>

                                </div>
                            </div>


                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" id="modalDialog">
                                    <div class="modal-content" id="modalContent">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <h5>Are you sure you need to update this data ? </h5>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <input type="submit" value="Update" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Modal -->

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



</section>

@section Scripts{
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

HRSystem/Views/AttentanceReport/Excel.cshtml
<form enctype="multipart/form-data" method="post" asp-controller="AttentanceReport" asp-action="ImportExcelFile">
    <dl>
        <dt>
            <label>Upload Excel:</label>
        </dt>
        <dd>
            <input type="file" name="FormFile" id="FormFile">

        </dd>
    </dl>
    <input class="btn" type="submit" value="Upload" />
</form>
<br/>
<div class="">
    <!--Show Message if file is uploaded or not-->
    @ViewBag.Message
</div>

HRSystem/Views/AttentanceReport/Index.cshtml
@model List<AttendanceReport>



<div class="card-body collapse show">
    <div class="card-block card-dashboard ">
        <div class="card-header">
            <div class="card-title-wrap bar-success">
                <h4 class="card-title">Attendance Report Information</h4>
            </div>
        </div>
        
        <div class="dataTables_length " id="DataTables_Table_0_length">
            <div class="card-body">
                <div class=" container m-auto">
                    <div class="row">

                    <form enctype="multipart/form-data" method="post" asp-controller="AttentanceReport" asp-action="ImportExcelFile">
                        <dl class="row g-3 align-items-center bg-light" >
                            <dt>
                                <label>Upload Excel:</label>
                            </dt>
                            <dd class="col-auto">
                                <input type="file" name="FormFile" id="FormFile">

                            </dd>
                             <input class="btn " type="submit" value="Upload" />
                        </dl>
                       
                    </form>
                    <div class=" form-group p-1 col-lg-3 col-md-5 col-sm-12">
                               
                            <a class="btn btn-success"style="margin-left:39px!important" asp-action="Create" asp-controller="AttentanceReport" id="idd" >+Add Employee Attendance</a>
                    </div>
                    </div>

                    <br />
                    <div class="">
                        <!--Show Message if file is uploaded or not-->
                        @ViewBag.Message
                    </div>
                    <form asp-action="Index" asp-controller="AttentanceReport">
                        <div class="row">

                            <div class=" form-group p-1 col-lg-5 col-md-5 col-sm-12">
                                <label for="EmpName ">Employee Name</label>
                                <input type="text" class="form-control col-lg-12" id="EmpName" name="EmpName" value="@ViewBag.EmpName">
                                <small class="form-text text-muted">Search with Employee Name.</small>
                                <span class="text-danger">@ViewBag.namerr</span>
                            </div>

                            <div class="form-group p-1 col-lg-5 col-md-5 col-sm-12">
                                <label for="DeptId">Department</label>
                                <select name="DeptId" id="DeptId" class="form-control col-lg-12 ">
                                    <option> --Select Department-- </option>
                                    @foreach (var dept in @ViewBag.Depts)
                                    {
                                        if (dept.Id == ViewBag.DeptId)
                                        {
                                            <option selected value="@dept.Id">@dept.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@dept.Id">@dept.Name</option>
                                        }
                                    }
                                </select>
                                <small class="form-text text-muted">Search with Department Name.</small>
                            </div>
                            <div>
                               
                            
                            </div>

                            <div class="form-group p-0 col-lg-5 col-md-5 col-sm-12">
                                <label class="label-control" for="DateFrom">From</label>
                                <div class="col-md-9">
                                    <input type="date" id="DateFrom" class="form-control col-lg-12" name="DateFrom" value="@ViewBag.DateFrom">
                                    <span class="text-danger">@ViewBag.msg</span>
                                </div>
                            </div>

                            <div class="form-group p-0 col-lg-5 col-md-5 col-sm-12">
                                <label class="label-control" for="DateTo">To</label>
                                <div class="col-md-9">
                                    <input type="date" id="DateTo" class="form-control col-lg-12" name="DateTo" value=@ViewBag.DateTo>
                                    <span class="text-danger">@ViewBag.msg</span>

                                </div>
                            </div>
                            <div class="p-0 col-lg-2 col-md-2 ">
                                <button type="submit" style="margin-top:39px!important" class="btn btn-primary col-lg-12 mt-4">Search</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="scroll">


            <table class="table table-striped table-bordered zero-configuration text-center text-truncate">
                <thead class="text-light bg-dark">
                    <tr>
                        <th>#</th>
                        <th>Employee Name</th>
                        <th>Department Name</th>
                        <th>Attendance Time</th>
                        <th>check-out Time</th>
                        <th>Date </th>
                        <th>Actions </th>

                    </tr>
                </thead>
                <tbody>
                    @{
                        var i = 0;
                    }
                    @foreach (var report in @Model)
                    {
                        <tr>
                            @{
                                i++;
                            }
                        </tr>
                        <tr>
                            <td>@i</td>
                            <td>@report.Employee.Name</td>
                            <td>@report.Employee.Department.Name</td>
                            <td>@report.AttendanceTime.TimeOfDay</td>
                            <td>@report.LeavingTime.TimeOfDay</td>
                            <td>@report.Date.Day/@report.Date.Month/@report.Date.Year,@report.Date.DayOfWeek</td>
                            <td>
                                <!-- Button trigger modal -->
                                 <a asp-action="Edit" asp-controller="AttentanceReport" asp-route-id="@report.Id" class="btn btn-success mr-1 ">Edit </a>
                                <a class="btn btn-danger" asp-action="Index" asp-controller="AttentanceReport" asp-route-id="@report.Id">Delete</a>
                                @*<button type="button" class="btn btn-danger pr-3 pl-3" data-toggle="modal" data-target="#exampleModal">Delete</button>*@
                            
                            </td>


                        </tr>

                    }
                </tbody>
            </table>
        </div>


    </div>
</div>



@if(@ViewBag.id != 0){
<!-- Modal -->

<div class="modal fade" id="exampleModal6" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" id="modalDialog">
        <div class="modal-content" id="modalContent">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Are you sure you need to delete this data ? </h5>
            </div>
            <div class="modal-footer">
                <a type="button" asp-action="Delete" asp-controller="AttentanceReport" asp-route-id="@ViewBag.id" class="btn btn-danger "> Delete </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
}

<!--********************************************************************-->

@section Scripts{
<script>
    $(window).on('load',function(){
    $('#exampleModal6').modal('show');
    });
</script>
<!--JQuery PAckage -->

<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}