HRSystem/Controllers/SalaryReportController.cs
using HRSystem.Models;
using HRSystem.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace HRSystem.Controllers
{
    public class SalaryReportController : Controller
    {
        IEmployeeRepository employeeRepository;

        IOfficialHolidaysRepository officialHolidaysRepository;
        IGeneralSettingRepository generalSettingServices;
        IAttentanceReportRepository attentanceReportRepository;

        public SalaryReportController(IEmployeeRepository employee, IOfficialHolidaysRepository official, IGeneralSettingRepository generalSetting, IAttentanceReportRepository attentanceReport)
        {
            employeeRepository = employee;
            generalSettingServices = generalSetting;
            officialHolidaysRepository = official;
            attentanceReportRepository = attentanceReport;

        }
        public IActionResult Index(string EmpName = null,int mnth=0,int year=0)
        {
            List<Employee> employees = employeeRepository.GetAll();
            List<AttendanceReport> reports = attentanceReportRepository.GetAll();
            GeneralSetting setting = generalSettingServices.Get();
            List<OfficialHolidays> officialHolidays = officialHolidaysRepository.GetAll();
            if (EmpName != null)
            {
                reports = reports.Where(e => e.Employee.Name.Contains(EmpName)).ToList();
                employees = employees.Where(e => e.Name.Contains(EmpName)).ToList();
            }
            int[] arr = {0,31,28,31,30,31,30,31,31,30,31,30,31 };
            int Days = arr[mnth]-8;

            foreach(var day in officialHolidays)
            {
                if(day.Date.Month == mnth && day.Date.Year == year)
                {
                    Days--;
                }
            }
            
            ViewData["Days"] = Days;
            ViewData["EmpName"] = EmpName;
            ViewData["year"] = year;
            ViewData["mnth"] = mnth;
            ViewData["setting"] = setting;
            ViewData["Holidays"] = officialHolidays;
            return View(employees);
        }

        
        public IActionResult Details(string EmpName="",string DeptName="",decimal Salary = 0, int AttendanceDays = 0, int AbsenceDays = 0, int bonusHours = 0, int DiscountHours = 0, decimal Totalbonus = 0, decimal TotalDiscount=0,decimal Total=0)
        {
            ViewData["EmpName"] = EmpName;
            ViewData["DeptName"] = DeptName;
            ViewData["Salary"] = Salary;
            ViewData["AttendanceDays"] = AttendanceDays;
            ViewData["AbsenceDays"] = AbsenceDays;
            ViewData["bonusHours"] = bonusHours;
            ViewData["DiscountHours"] = DiscountHours;
            ViewData["Totalbonus"] = Totalbonus;
            ViewData["TotalDiscount"] = TotalDiscount;
            ViewData["Total"] = Total;
            return View();
        }
    }
}

HRSystem/Views/SalaryReport/Details.cshtml
                                <!-- Invoice Company Details -->
                                <div id="invoice-company-details" class="row">
                                    <div class="col-6 text-left">
                                        <img src="../app-assets/img/logo.png" alt="company logo" class="mb-2" width="70">
                                        <ul class="px-0 list-unstyled">
                                            <li class="text-bold-800">Pioneer Solutions Company </li>
                                            <li>Cairo,</li>
                                            <li>Naser City ,</li>
                                            <li>102 Makrim Ebid,</li>
                                           
                                        </ul>
                                    </div>
                                   
                                </div>
                     
                                <!--/ Invoice Customer Details -->
                                <!-- Invoice Items Details -->
                                <div id="invoice-items-details" class="pt-2">
                                    <div class="row">
                            <div class="scroll">
                                        
                                      <table class="table table-striped table-bordered zero-configuration mt-40">
                                        <thead class="text-light bg-dark">
                                        <tr class="text-center text-truncate">
                                            <th>Name</th>
                                            <th>Department</th>
                                            <th>Salary</th>
                                            <th>Attendance Days</th>
                                            <th>Absence Days</th>
                                            <th>bonus Hours</th>
                                            <th>Discount Hours</th>
                                            <th>Total Bonus</th>
                                            <th>Total Discount</th>
                                            <th>Total</th>
                                     
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@ViewBag.EmpName</td>
                                                <td>@ViewBag.DeptName</td>
                                                <td>$@ViewBag.Salary</td>
                                                <td>@ViewBag.AttendanceDays Day</td>
                                                <td>@ViewBag.AbsenceDays Day</td>
                                                <td>@ViewBag.bonusHours Hour</td>
                                                <td>@ViewBag.DiscountHours Hour</td>
                                                <td>$@ViewBag.Totalbonus</td>
                                                <td>$@ViewBag.TotalDiscount</td>
                                                <td>$@ViewBag.Total</td>
                                            </tr>
                                   
                                          
                                      
                                                                                                                                                                                                                                                                                 
                                        </tbody>
                            
                                    </table>
                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6 col-sm-12 text-left">
                                            <p class="lead">Payment Methods:</p>
                                            <div class="row">
                                                <div class="col-12">
                                                    <table class="table table-borderless table-sm">
                                                        <tbody>
                                                            <tr>
                                                                <td>Bank name:</td>
                                                                <td class="text-right">ABC Bank, USA</td>
                                                            </tr>
                                                            <tr>
                                                                <td>Acc name:</td>
                                                                <td class="text-right">Amanda Orton</td>
                                                            </tr>
                                                            <tr>
                                                                <td>IBAN:</td>
                                                                <td class="text-right">FGS165461646546AA</td>
                                                            </tr>
                                                            <tr>
                                                                <td>SWIFT code:</td>
                                                                <td class="text-right">BTNPP34</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-md-6 col-sm-12">
                                            <p class="lead">Total due</p>
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>Sub Total</td>
                                                            <td class="text-right">$ @ViewBag.Total</td>
                                                        </tr>
                                                        <tr>
                                                            <td>TAX (0%)</td>
                                                            <td class="text-right">$ 0</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-bold-800">Total</td>
                                                            <td class="text-bold-800 text-right"> $ @ViewBag.Total</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="text-center">
                                                <p>Authorized person</p>
                                                <img src="../app-assets/img/pages/signature-scan.png" alt="signature" class="width-250">
                                                <h6>Amanda Orton</h6>
                                                <p class="text-muted">Managing Director</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Invoice Footer -->
                                <div id="invoice-footer">
                                    <div class="row">
                                        <div class="col-md-9 col-sm-12">
                                            <h6>Terms &amp; Condition</h6>
                                            <p>You know, being a test pilot isn't always the healthiest business in the world. We predict too
                                                much for the next year and yet far too little for the next 10.</p>
                                        </div>
                                        <div class="col-md-3 col-sm-12 text-center">
                                            <button type="button" class="btn btn-primary my-1" onclick="window.print()"><i class="fa fa-paper-plane-o"></i> Print</button>
                                        </div>
                                    </div>
                                </div>
                                <!--/ Invoice Footer -->
                            
        <footer class="footer footer-static footer-light">
          <p class="clearfix text-muted text-center px-2"><span>Copyright  &copy; 2021 <a href="#" id="pixinventLink" target="_blank" class="text-bold-800 primary darken-2">Pioneer solutions </a>, All rights reserved. </span></p>
        </footer>

     
    <!-- ////////////////////////////////////////////////////////////////////////////-->

HRSystem/Views/SalaryReport/Index.cshtml
@model List<Employee>

<section id="configuration" class="container">

    <div class="container">
        <div class="card-header">
            <div class="card-title-wrap bar-success">
                <h4 class="card-title">Salary Report Information</h4>
            </div>
        </div>
        <div class="card-body collapse show  m-auto">
            <div class="card-block card-dashboard ">

                <div class="row col-lg-12" style="position:relative">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="dataTables_length " id="DataTables_Table_0_length">

                            <div class="card-body">
                                <div class=" container m-auto ">

                                    <form asp-action="" asp-controller="SalaryReport">
                                        <div class="row">


                                            <div class=" form-group p-3 col-lg-3 col-md-4 col-sm-12">
                                                <label for="exampleInputEmail1">Emp Name</label>
                                                <input required type="text" class="form-control col-lg-12" id="exampleInputEmail1" name="EmpName" value="@ViewBag.EmpName">
                                                <small class="form-text text-muted">Employee Name</small>
                                                <span class="text-danger">@ViewBag.EmpErrMSG</span>
                                            </div>

                                            <div class=" form-group p-3 col-lg-3 col-md-4 col-sm-12">
                                                <label for="mnth">Month</label>
                                                <input min="1" max="12" required type="number" class="form-control col-lg-12" id="mnth" name="mnth" value="@ViewBag.mnth">
                                                <small class="form-text text-muted">Search with month</small>
                                            </div>
                                            <div class=" form-group p-3 col-lg-3 col-md-4 col-sm-12">
                                                <label for="year">Year</label>
                                                <input min="2008" required type="number" class="form-control col-lg-12" id="year" name="year" value="@ViewBag.year">
                                                <small class="form-text text-muted">Search with year</small>
                                            </div>

                                            <div class="form-group p-3 col-lg-3 col-sm-12 ">
                                                <button type="submit" style="margin-top:39px!important" class="btn btn-primary col-lg-12 mt-4">Search</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        @if (@ViewBag.year != 1 && ViewBag.EmpName != null)
                        {

                            <div class="scroll">


                                <table class="table table-striped table-bordered zero-configuration">
                                    <thead class="text-light bg-dark">
                                        <tr class="text-center text-truncate">
                                            <th>Name</th>
                                            <th>Department</th>
                                            <th>Salary</th>
                                            <th>Attendance Days</th>
                                            <th>Absence Days</th>
                                            <th>bonus Hours</th>
                                            <th>Discount Hours</th>
                                            <th>Total Bonus</th>
                                            <th>Total Discount</th>
                                            <th>Total</th>
                                            <th>Details</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var EMP in @Model)
                                        {
                                            <tr>

                                                @{
                                                    var AttendanceHours = @EMP.LeavingTime.Hour - @EMP.AttendanceTime.Hour;
                                                    var AttendanceMinute = @EMP.LeavingTime.Minute - @EMP.AttendanceTime.Minute;
                                                    var AttendanceDays = 0;
                                                    var AbsenceDays = 0;
                                                    var DiscountHours = 0;
                                                    var bonusHours = 0;
                                                    decimal TotalDiscount = 0;
                                                    decimal Totalbonus = 0;
                                                    decimal Total = 0;
                                                    decimal Salary = 0;
                                                    decimal daySalary = @EMP.Salary / @ViewBag.Days;
                                                    decimal TotalAbsenceDiscount = 0;
                                                }

                                                @if (@EMP.attendanceReports != null)
                                                {
                                                    @foreach (var report in @EMP.attendanceReports)
                                                    {
                                                        @*<td>@report.EmpId</td>*@

                                                        if (report.Date.Year == ViewBag.year && report.Date.Month == ViewBag.mnth)
                                                        {

                                                            if ((report.LeavingTime.Hour - report.AttendanceTime.Hour) == AttendanceHours)
                                                            {
                                                                AttendanceDays++;
                                                            }
                                                            else if ((report.LeavingTime.Hour - report.AttendanceTime.Hour) > AttendanceHours)
                                                            {
                                                                AttendanceDays++;
                                                                bonusHours += (report.LeavingTime.Hour - report.AttendanceTime.Hour) - AttendanceHours;
                                                                Totalbonus = bonusHours * (@ViewBag.setting.ExtraHours);
                                                            }
                                                            else if ((report.LeavingTime.Hour - report.AttendanceTime.Hour) < AttendanceHours)
                                                            {
                                                                AttendanceDays++;
                                                                DiscountHours += AttendanceHours - (report.LeavingTime.Hour - report.AttendanceTime.Hour);
                                                                TotalDiscount = DiscountHours * (@ViewBag.setting.DiscountHours);
                                                            }
                                                            AbsenceDays = @ViewBag.Days - AttendanceDays;

                                                            TotalAbsenceDiscount = daySalary * AbsenceDays;
                                                            TotalAbsenceDiscount = Math.Round(TotalAbsenceDiscount, 2);

                                                            Total = @EMP.Salary + @Totalbonus - @TotalDiscount - @TotalAbsenceDiscount;
                                                            Salary = @EMP.Salary;
                                                        }
                                                    }
                                                    TotalDiscount += TotalAbsenceDiscount;
                                                }

                                                <td>@EMP.Name</td>
                                                <td>@EMP.Department.Name</td>
                                                <td>$@Salary </td>
                                                <td>@AttendanceDays Day</td>
                                                <td>@AbsenceDays Day</td>
                                                <td>@bonusHours Hour</td>
                                                <td>@DiscountHours Hour</td>
                                                <td>$@Totalbonus</td>
                                                <td>$@TotalDiscount</td>
                                                <td>$@Total</td>
                                                <td>
                                                    <a class="btn btn-danger" asp-action="Details" asp-controller="SalaryReport"  asp-route-EmpName="@EMP.Name&DeptName" asp-route-DeptName="@EMP.Department.Name" asp-route-Salary="@Salary"  asp-route-AttendanceDays="@AttendanceDays" asp-route-AbsenceDays="@AbsenceDays" asp-route-bonusHours="@bonusHours" asp-route-DiscountHours="@DiscountHours"  asp-route-Totalbonus="@Totalbonus"   asp-route-TotalDiscount="@TotalDiscount"  asp-route-Total="@Total"   > Details </a>
                                                </td>

                                            </tr>

                                        }
                                    </tbody>
                                </table>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>

</section>